### ISSUE TITLE
starlink.Ast.Channel.write() argument 1 must be starlink.Ast.Object, not None

### ISSUE THREAD

**Issue by keflavich** [msgordon/starlink-sdf#1]
I encountered the traceback below when trying to convert some files from this (public) repository to FITS:
https://www.canfar.net/storage/list/AstroDataCitationDOI/CISTI.CANFAR/17.0009/data

```python
$ sdf2fits 850um_map.sdf 850um_map.fits
Traceback (most recent call last):
  File "/orange/adamginsburg/miniconda3/bin/sdf2fits", line 33, in <module>
    sys.exit(load_entry_point('starlink-sdf==0.5', 'console_scripts', 'sdf2fits')())
  File "/orange/adamginsburg/miniconda3/lib/python3.7/site-packages/starlink_sdf-0.5-py3.7.egg/starlink/sdf/sdf.py", line 387, in main
    hdu = sdfopen(args.filename)
  File "/orange/adamginsburg/miniconda3/lib/python3.7/site-packages/starlink_sdf-0.5-py3.7.egg/starlink/sdf/sdf.py", line 368, in sdfopen
    hdlist = list(hdlist)
  File "/orange/adamginsburg/miniconda3/lib/python3.7/site-packages/starlink_sdf-0.5-py3.7.egg/starlink/sdf/sdf.py", line 366, in <genexpr>
    hdlist = (getdata(hd,ext,as_hdu=True) for ext in exts)
  File "/orange/adamginsburg/miniconda3/lib/python3.7/site-packages/starlink_sdf-0.5-py3.7.egg/starlink/sdf/sdf.py", line 346, in getdata
    data = extract_data(filename, **opts)
  File "/orange/adamginsburg/miniconda3/lib/python3.7/site-packages/starlink_sdf-0.5-py3.7.egg/starlink/sdf/sdf.py", line 310, in extract_data
    with_wcs=with_wcs)
  File "/orange/adamginsburg/miniconda3/lib/python3.7/site-packages/starlink_sdf-0.5-py3.7.egg/starlink/sdf/sdf.py", line 233, in extract_header
    wcs = extract_wcs(data, wcs_path)
  File "/orange/adamginsburg/miniconda3/lib/python3.7/site-packages/starlink_sdf-0.5-py3.7.egg/starlink/sdf/sdf.py", line 182, in extract_wcs
    Atl.writefitswcs(fs, hdu)
  File "/orange/adamginsburg/miniconda3/lib/python3.7/site-packages/starlink_pyast-3.15.3-py3.7-linux-x86_64.egg/starlink/Atl.py", line 283, in writefitswcs
    return fitschan.write(frameset)
TypeError: starlink.Ast.Channel.write() argument 1 must be starlink.Ast.Object, not None
```

**Comment by msgordon** [comment]
Ah sorry about that, and thanks for using this package!  This issue seems to arise from a less-than-ideal method of reading the WCS information from the header.  To reduce the complexity in converting Starlink FrameSets to WCS objects, the FrameSet string makes a round trip through a temporary file into an Ast.Channel.  Starlink Ast seems to take issue on certain platforms reading the FrameSet from a file that is still open.  I have updated the file read/write logic to avoid this potential race condition or I/O issue.

   Try another pip install/git pull and try again with version 0.6 (just pushed), and kindly let me know if the issue is resolved.
